version: '3.8'

services:
  # Backend Flask API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: web_zui_backend
    ports:
      - "5000:5000"
    env_file:
      - .env.docker
    volumes:
      - ./backend/uploads:/app/uploads
    networks:
      - web_zui_network
    restart: unless-stopped

  # Frontend React App
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: web_zui_frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:5000/api
    depends_on:
      - backend
    networks:
      - web_zui_network
    restart: unless-stopped

networks:
  web_zui_network:
    driver: bridge
