version: '3.8'

services:
  # Backend Flask API - INTERNAL ONLY
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: web_zui_backend
    # Remove ports exposure - only internal access
    env_file:
      - .env.docker
    volumes:
      - ./backend/uploads:/app/uploads
    networks:
      - web_zui_network
    restart: unless-stopped

  # Frontend React App - PUBLIC ACCESS
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: web_zui_frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=/api  # Use relative path for proxy
    depends_on:
      - backend
    networks:
      - web_zui_network
    restart: unless-stopped

networks:
  web_zui_network:
    driver: bridge
